# Add application configuration variables here, as shown below.

GMAIL_USERNAME: budisugianto777@gmail.com
GMAIL_PASSWORD: Bs420203544

AWS_ACCESS_ID:  AKIAJGI57SVRMXAXNDSQ
AWS_SECRET_ID:  2wNBKQaWxqfCQFaNlVN6YKK1eJYDS8SvN9lPHWv9

RECAPTCHA_PUBLIC_KEY: 6LcVf-MSAAAAAJxcLnH2a48Wiwywu_j0wsgBaZg7
RECAPTCHA_PRIVATE_KEY: 6LcVf-MSAAAAAM0JNspKtZRey4r6akuri2WwSV_C

RPX_APP_ID: cgmkindjfikiifmlamfl
RPX_API_KEY: 06195c9e235e23dfcb425e85ef0651a8386e5564

